# default: flies along the wall independently
# line: flies along the wall but manages the distances of the neighbors.
# mesh: (not implemented yet)
auto_pilot_type: mesh # default, line, mesh

robots:
  - robot1
  - robot2
  - robot3
  - robot4
  - robot5
  - robot6
  - robot7
  - robot8
  - robot9
  - robot10

robot1:
  x: 0.0
  y: -8.0
  z: 1.2
  Y: 0.0
  #Y: -1.570796
  map_only: false
  map_filename: ''
  output: screen # screen, log
  save_traj: false

robot2:
  x: -2.0
  y: -5.0
  z: 0.5
  Y: 0.0
  map_only: false
  map_filename: ''
  output: screen

robot3:
  x: 2.0
  y: 0.0
  z: 0.31
  Y: 0
  map_only: false
  map_filename: ''
  output: screen
  save_traj: false

robot4:
  x: -16
  y: 2
  Y: -3.14159265
  map_only: false
  map_filename: ''
  output: screen

robot5:
  x: -8
  y: 2
  Y: 3.14159265
  map_only: false
  map_filename: ''
  output: screen

robot6:
  x: 0
  y: 2
  Y: 3.14159265
  map_only: false
  map_filename: ''
  output: screen

robot7:
  x: 8
  y: 2
  Y: 3.14159265
  map_only: false
  map_filename: ''
  output: screen

robot8:
  x: 16
  y: 2
  Y: 3.14159265
  map_only: false
  map_filename: ''
  output: screen

robot9:
  x: 16
  y: -2
  Y: 0
  map_only: false
  map_filename: ''
  output: screen

robot10:
  x: 8
  y: -2
  Y: 0
  map_only: false
  map_filename: ''
  output: screen
